version: "3.7"

services:
  netdata:
    labels:
      traefik.enable: "true"
      traefik.docker.network: homelab_default
      traefik.http.routers.netdata.tls.certresolver: prod
      traefik.http.routers.netdata.rule: Host(`${NETDATA_HOST}`)
      traefik.http.routers.netdata.middlewares: hsts-header, traefik-forward-auth

  traefik-forward-auth:
    labels:
      traefik.enable: "true"
      traefik.http.routers.traefik-forward-auth.tls.certresolver: prod
      traefik.http.routers.traefik-forward-auth.rule: Host(`${AUTH_HOST}`)
      traefik.http.routers.traefik-forward-auth.middlewares:  traefik-forward-auth
      traefik.http.middlewares.traefik-forward-auth.forwardauth.address: http://traefik-forward-auth:4181
      traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders: X-Forwarded-User
      traefik.http.services.traefik-forward-auth.loadbalancer.server.port: 4181

  home:
    labels:
      traefik.enable: "true"
      traefik.http.routers.home.tls.certresolver: prod
      traefik.http.routers.home.rule: Host(`${HOME_ASSISTANT_HOST}`)
      traefik.http.routers.home.middlewares: hsts-header
      traefik.http.services.home.loadbalancer.server.port: 8123
      traefik.http.services.home.loadbalancer.server.scheme: http

  esphome:
    labels:
      traefik.enable: "true"
      traefik.docker.network: homelab_default
      traefik.http.routers.esphome.tls.certresolver: prod
      traefik.http.routers.esphome.rule: Host(`${ESPHOME_HOST}`)
      traefik.http.routers.esphome.middlewares: hsts-header, traefik-forward-auth
      traefik.http.services.esphome.loadbalancer.server.port: 6052
      traefik.http.services.esphome.loadbalancer.server.scheme: http

  code:
    labels:
      traefik.enable: "true"
      traefik.docker.network: homelab_default
      traefik.http.routers.code.tls.certresolver: prod
      traefik.http.routers.code.rule: Host(`${CODE_HOST}`)
      traefik.http.routers.code.middlewares: hsts-header, traefik-forward-auth
      traefik.http.services.code.loadbalancer.server.port: ${CODE_PORT}
      traefik.http.services.code.loadbalancer.server.scheme: http

  personal-site:
    labels:
      traefik.enable: "true"
      traefik.docker.network: homelab_default
      traefik.http.routers.personal-site.tls.certresolver: prod
      traefik.http.routers.personal-site.rule: "Host(`${PERSONAL_SITE_HOST}`) || Host(`${COOKIE_DOMAIN}`)"
      traefik.http.routers.personal-site.middlewares: hsts-header
      traefik.http.routers.personal-site-dashboard.tls.certresolver: prod
      traefik.http.routers.personal-site-dashboard.rule: "(Host(`${PERSONAL_SITE_HOST}`) || Host(`${COOKIE_DOMAIN}`)) && PathPrefix(`${DASHBOARD_PATH}`)"
      traefik.http.routers.personal-site-dashboard.middlewares: hsts-header, traefik-forward-auth
      traefik.http.services.personal-site.loadbalancer.server.port: ${WWW_PORT}
      traefik.http.services.personal-site.loadbalancer.server.scheme: http

  adguard:
    labels:
      traefik.enable: "true"
      traefik.http.routers.adguard.tls.certresolver: prod
      traefik.http.routers.adguard.rule: Host(`${ADGUARD_HOST}`)
      traefik.http.routers.adguard.middlewares: hsts-header
      # Be sure to configure this after install to bind to this port instead of 80!
      traefik.http.services.adguard.loadbalancer.server.port: 3333 
      traefik.http.services.adguard.loadbalancer.server.scheme: http

  portainer:
    labels:
      traefik.enable: "true"
      traefik.http.routers.portainer.tls.certresolver: prod
      traefik.http.routers.portainer.rule: Host(`${PORTAINER_HOST}`)
      traefik.http.routers.portainer.middlewares: hsts-header
      traefik.http.services.portainer.loadbalancer.server.port: 9000
      traefik.http.services.portainer.loadbalancer.server.scheme: http

  unifi:
    labels:
      traefik.enable: "true"
      traefik.http.routers.unifi.tls.certresolver: prod
      traefik.http.routers.unifi.rule: Host(`${UNIFI_HOST}`)
      traefik.http.routers.unifi.middlewares: hsts-header
      traefik.http.services.unifi.loadbalancer.server.port: 8443
      traefik.http.services.unifi.loadbalancer.server.scheme: https

  bookstack:
    labels:
      traefik.enable: "true"
      traefik.http.routers.bookstack.tls.certresolver: prod
      traefik.http.routers.bookstack.rule: Host(`${BOOKSTACK_HOST}`)
      traefik.http.routers.bookstack.middlewares: hsts-header
      traefik.http.services.bookstack.loadbalancer.server.port: 80
      traefik.http.services.bookstack.loadbalancer.server.scheme: http

  mosquitto:
    labels:
      traefik.enable: "true"
      traefik.tcp.routers.mosquitto.tls.certresolver: prod
      traefik.tcp.routers.mosquitto.entrypoints: mqtt
      traefik.tcp.routers.mosquitto.rule: HostSNI(`${MOSQUITTO_HOST}`)
      traefik.tcp.services.mosquitto.loadbalancer.server.port: 1883
      traefik.http.routers.mosquitto-socket.tls.certresolver: prod
      traefik.http.routers.mosquitto-socket.entrypoints: websecure
      traefik.http.routers.mosquitto-socket.rule: Host(`${MOSQUITTO_HOST}`)
      traefik.http.services.mosquitto-socket.loadbalancer.server.port: 9001


  # https://hub.docker.com/_/traefik/
  traefik:
    image: traefik:latest
    restart: unless-stopped
    environment:
      TZ: "${TZ}"
      CF_API_EMAIL: "${CF_API_EMAIL}"
      CF_API_KEY: "${CF_API_KEY}"
    networks:
      - default
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 8883:8883/tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/log:/var/log
      - ./traefik:/etc/traefik:rw
    dns:
      - 1.1.1.1
      - 1.0.0.1
    labels:
      traefik.enable: "true"
      traefik.docker.network: homelab_default
      traefik.http.routers.traefik.tls.certresolver: prod
      traefik.http.routers.traefik.rule: Host(`${TRAEFIK_HOST}`)
      traefik.http.routers.traefik.middlewares: hsts-header, traefik-forward-auth
      traefik.http.routers.traefik.service: api@internal
      traefik.http.middlewares.test-auth.basicauth.users: "${BASICAUTH_USERS}"
      traefik.http.middlewares.basicauth.basicauth.usersfile: /etc/traefik/.htpasswd
      traefik.http.middlewares.ipallowlist.ipwhitelist.sourcerange: "${IPALLOWLIST}"
      traefik.http.middlewares.hsts-header.headers.customResponseHeaders.Strict-Transport-Security: "max-age=63072000"
    extra_hosts:
      - host.docker.internal:172.17.0.1
